[package]
name = "contrasted"
description = "Simple library for checking the contrast between two colors."
version = "0.1.2"
edition = "2024"
authors = ["trisuaso"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/trisuaso/contrasted"

[dependencies]
